MODULE ProjectMaterialLineCustom;

REQUIRE ProjectCustom, ItemCustom, ProjectTechnicalSolutionCustom;

NAMESPACE ProjectManagement;

@defineProjectHistoryLine(project, ProjectMaterialLine, material, 'Изменен материал', nameMaterial);
@defineProjectHistoryLineProperty(project, ProjectMaterialLine, uom, 'Материал - изменена ед. изм.', nameMaterial);
@defineProjectHistoryLineProperty(project, ProjectMaterialLine, initialDemand, 'Материал - Планируемое кол-во', nameMaterial);
@defineProjectHistoryLineProperty(project, ProjectMaterialLine, done, 'Материал - Кол-во (выполненное)', nameMaterial);