MODULE ProjectServiceLineCustom;

REQUIRE ProjectCustom, ServiceP, ProjectTechnicalSolutionCustom;

NAMESPACE ProjectManagement;

@defineProjectHistoryLine(project, ProjectServiceLine, service, 'Изменена работа', nameService);
@defineProjectHistoryLineProperty(project, ProjectServiceLine, uom, 'Работа - изменена ед. изм.', nameService);
@defineProjectHistoryLineProperty(project, ProjectServiceLine, initialDemand, 'Работа - Планируемое кол-во', nameService);
