MODULE MyCompanyCustom;

REQUIRE Eval, ProcessMonitor, Backup,
        ItemAttribute, ProjectCustom,
        ProjectLegalEntityRoleCustom,
        CategoryCustom, ItemCustom, 
        ServiceP,
        ProjectServiceLineCustom, ProjectMaterialLineCustom, ProjectEquipmentLineCustom,
        InventorySettings, CategoryLot,
        BrigadeEmployeeRoleCustom, BrigadeCustom, StandardTechnicalSolutionCustom,
        ItemAnalogCustom;